version: "3.3"

services:
  asp:
    image: grahamh/aspnet-sample:2.0
    ports:
      - "8082:80"
    networks:
      - aspnet
    deploy:
      replicas: 2
      placement:
        constraints:
          - 'node.platform.os == windows'

networks:
  aspnet:
    driver: overlay
